# Generated by Django 5.0.6 on 2024-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
    ]
