# Generated by Django 5.0.6 on 2024-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(default='other', max_length=255)),
                ('description', models.CharField(default='', max_length=1000)),
                ('price', models.IntegerField(default=80000)),
            ],
        ),
    ]
