# Generated by Django 5.0.6 on 2024-05-27 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user')),
            ],
        ),
    ]
